### ISSUE TITLE
Are there any tools to extract/flash firmware on the Balong 5000 based 'Huawei 5G CPE PRO 2'?

### ISSUE THREAD

**Issue by ghost** [Huawei-LTE-routers-mods/balong-raw-dump-tools#1]
sorry if this is the wrong place;
Are there any tools to extract/flash firmware on the Balong 5000 based 'Huawei 5G CPE PRO 2' (H122-373)?

**Comment by ValdikSS** [comment]
Balongflash successfully extracts and flashes E6878 and H122 firmware.

**Comment by SKETCH-1** [comment]
After installing the wrong update, the router h122-373 stopped working, it only works with the usb port. we need the Balong_USB_Loader_h122-373 file to repair the router

**Comment by pasan001** [comment]
Have you fixed the router?

**Comment by radikal357** [comment]
hello, does anyone here have the h122-373-A firmware?
