### ISSUE TITLE
Cpe pro 2 

### ISSUE THREAD

**Issue by VanitasX** [Huawei-LTE-routers-mods/balong-raw-dump-tools#2]
Hello Valdikss, I tried contacting you on your email address and I made post on the forum but I don't know if you saw it.. 
So please I have a question if you don't mind, 
I have a CPE pro 2 router unlocked global version (C00) but I installed a Chinese update and WEBUI  (C233) on it. Is there's anyway I can return back to global (C00) update?

**Comment by ValdikSS** [comment]
As far as I know, there's no public method to flash back global version.
