### ISSUE TITLE
h112-372

### ISSUE THREAD

**Issue by Putative** [Huawei-LTE-routers-mods/balong-raw-dump-tools#4]
Not sure how any of these work, I've only flashed a B315 before. i've got the H112-372, is there a way to get the firmware for it and flash it? I'd appreciate the help.

**Comment by ValdikSS** [comment]
It's not possible to construct flashable firmware from the NAND dump right away.
It's possible to reconstruct the firmware, however the signature of the firmware won't be correct (the firmware includes file partitions as cpio images, while NAND dump does not have them, but contains the unpacked files). It _might_ be possible to reconstruct the cpio files to get working signature, but it's quite challenging at least.

**Comment by Putative** [comment]
I've got the firmwares from easyfirmware, is there any way to use that to load it to overcome the sim lock?

**Comment by ValdikSS** [comment]
No, probably not.

**Comment by Putative** [comment]
So is my router a dud without the original sim? 😔

**Comment by ValdikSS** [comment]
Yes, I'm afraid. At least for now.
